# Generated by Django 5.2.1 on 2025-05-29 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etablissement',
            fields=[
                ('id_etablissement', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nom_etablissement', models.CharField(max_length=50)),
                ('email_pro', models.EmailField(max_length=50, unique=True)),
                ('numtel', models.CharField(max_length=50)),
                ('adresse_physique', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('password_hash', models.CharField(max_length=128)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(default='<function uuid4 at 0x7f5df3487240>', max_length=36)),
            ],
        ),
    ]
