# Generated by Django 5.2.1 on 2025-05-29 14:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_etablissement_id_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='verification_token',
            field=models.CharField(default=uuid.uuid4, max_length=36),
        ),
    ]
