# Generated by Django 5.2.1 on 2025-06-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_allergene_ingredient_jour_personne_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donner_avis',
            unique_together={('id_etablissement', 'date_avis')},
        ),
        migrations.RemoveField(
            model_name='donner_avis',
            name='id_personne',
        ),
    ]
