# Generated by Django 5.2.1 on 2025-06-17 03:28

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_donner_avis_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donner_avis',
            name='id',
        ),
        migrations.AddField(
            model_name='donner_avis',
            name='id_avis',
            field=models.CharField(default=core.models.generate_uuid, max_length=50, primary_key=True, serialize=False),
        ),
    ]
