# Generated by Django 5.2.1 on 2025-06-17 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_donner_avis_id_donner_avis_id_avis'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donner_avis',
            unique_together={('id_etablissement', 'date_avis', 'id_avis')},
        ),
    ]
