# Generated by Django 5.2.1 on 2025-06-17 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_donner_avis_description'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donner_avis',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='donner_avis',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='donner_avis',
            unique_together={('id_etablissement', 'date_avis', 'id_avis', 'description')},
        ),
    ]
