# Generated by Django 5.2.1 on 2025-06-17 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_donner_avis_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='donner_avis',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='donner_avis',
            name='id_item',
            field=models.ForeignKey(blank=True, default=25, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.item'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='donner_avis',
            unique_together={('id_etablissement', 'date_avis', 'id_avis', 'description', 'id_item')},
        ),
    ]
