# Generated by Django 5.2.1 on 2025-05-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_etablissement_id_etablissement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etablissement',
            name='id_etablissement',
            field=models.CharField(default='<function uuid4 at 0x772a28267240>', max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='verification_token',
            field=models.CharField(default='<function uuid4 at 0x772a28267240>', max_length=36),
        ),
    ]
