# Generated by Django 5.2.1 on 2025-05-29 17:14

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_etablissement_id_etablissement_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergene',
            fields=[
                ('id_allergene', models.AutoField(primary_key=True, serialize=False)),
                ('nom_allergene', models.CharField(max_length=50)),
                ('categorie_allergene', models.CharField(max_length=50)),
                ('dangerosite', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id_ingredient', models.AutoField(primary_key=True, serialize=False)),
                ('nom_ingredient', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('categorie', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Jour',
            fields=[
                ('id_jour', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personne',
            fields=[
                ('id_personne', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('geolocalisation', models.CharField(blank=True, max_length=255)),
                ('marque_tel', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='email_pro',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='password_hash',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='etablissement',
            name='verification_token',
            field=models.CharField(default=core.models.generate_uuid, max_length=50),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id_category', models.CharField(default=core.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='core.etablissement')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.CharField(max_length=50)),
                ('id_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nom_plat', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('disponibilite', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prep_time', models.IntegerField()),
                ('categories', models.ManyToManyField(related_name='items', to='core.category')),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.etablissement')),
                ('ingredients', models.ManyToManyField(through='core.Contenir', to='core.ingredient')),
                ('jours_disponibilite', models.ManyToManyField(related_name='items', to='core.jour')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id_image', models.AutoField(primary_key=True, serialize=False)),
                ('url_image', models.ImageField(upload_to='items_images/')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='contenir',
            name='id_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item'),
        ),
        migrations.CreateModel(
            name='Constituer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('id_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.item')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id_menu', models.CharField(default=core.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='core.etablissement')),
                ('items', models.ManyToManyField(through='core.Constituer', to='core.item')),
            ],
        ),
        migrations.AddField(
            model_name='constituer',
            name='id_menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.menu'),
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id_qrcode', models.CharField(default=core.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scans', models.IntegerField(default=0)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='core.menu')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id_tag', models.CharField(default=core.models.generate_uuid, max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.etablissement')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='tags',
            field=models.ManyToManyField(related_name='items', to='core.tag'),
        ),
        migrations.CreateModel(
            name='Contenir_Allergene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_allergene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allergene')),
                ('id_ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ingredient')),
            ],
            options={
                'unique_together': {('id_ingredient', 'id_allergene')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('id_item', 'id_ingredient')},
        ),
        migrations.CreateModel(
            name='Donner_Avis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_avis', models.DateField(auto_now_add=True)),
                ('note', models.IntegerField()),
                ('id_etablissement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='core.etablissement')),
                ('id_personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personne')),
            ],
            options={
                'unique_together': {('id_personne', 'id_etablissement', 'date_avis')},
            },
        ),
        migrations.CreateModel(
            name='Concerner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_allergene', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.allergene')),
                ('id_personne', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.personne')),
            ],
            options={
                'unique_together': {('id_personne', 'id_allergene')},
            },
        ),
    ]
